apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: default
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: registry:2.8.3
          name: registry
          ports:
            - containerPort: 5000
              name: registry

---

apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: registry
