apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-graalvm
spec:
  selector:
    matchLabels:
      app: jenkins-graalvm
  template:
    metadata:
      labels:
        app: jenkins-graalvm
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
        - name: jenkins-graalvm
          image: docker.local:5000/jenkins-graalvm:latest
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          volumeMounts:
            - name: jenkins-data
              mountPath: "/var/jenkins_home"
            - name: docker-bin
              mountPath: "/usr/bin/docker"
            - name: docker-sock
              mountPath: "/var/run/docker.sock"
            - name: gradle-home
              mountPath: "/root/.gradle"
          resources:
            limits:
              memory: 6Gi
            requests:
              memory: 1Gi
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
        - name: docker-bin
          hostPath:
            path: "/usr/bin/docker"
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"
        - name: gradle-home
          hostPath:
            path: "/mnt/data/jenkins/.gradle"
---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-graalvm-service
spec:
  selector:
    app: jenkins-graalvm
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-graalvm-jnlp
spec:
  selector:
    app: jenkins-graalvm
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
