apiVersion: v1
kind: Pod
metadata:
  name: git
  #labels:
    #traefik.http.routers.git.rule: Host(`git.dev.local`)
    #traefik.http.services.git.loadbalancer.server.port: 3000
spec:
  containers:
  - name: gitea
    image: docker.gitea.com/gitea:1.24.3
    ports:
    - containerPort: 3000
      hostPort: 3000
      protocol: TCP
    env:
    - name: USER_UID
      value: 1000
    - name: USER_GID
      value: 1000
    volumeMounts:
      - mountPath: /data:z
        name: gitea
  restartPolicy: Always
  dnsPolicy: Default
  volumes:
    - name: gitea
      hostPath:
        path: /home/vm1/.data/gitea
        type: Directory
