apiVersion: v1
kind: Pod
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  containers:
  - name: platform_traefik
    image: docker.io/library/traefik:3.5.0
    securityContext:
      privileged: true
    args:
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.mysql.address=:3306"
      - "--log.level=info"
      - "--providers.docker=true"
    ports:
      - containerPort: 8000
        hostPort: 8000
        protocol: TCP
      - containerPort: 8080
        hostPort: 8001
        protocol: TCP
      - containerPort: 3306
        hostPort: 3306
        protocol: TCP
    volumeMounts:
      - mountPath: /var/run/docker.sock:z
        name: docker_sock
  restartPolicy: Never
  dnsPolicy: Default
  volumes:
    - name: docker_sock
      hostPath:
        path: "/run/user/1000/podman/podman.sock"
        type: File
